### ISSUE TITLE
Data plane status incorrect

### ISSUE THREAD

**Issue by thesse1** [SoftwareAG/webmethods-api-control-plane#30] opened 2023-09-02 09:05 UTC
Sometimes, the data plane status does not correspond with the statuses of the included runtimes:

![image](https://github.com/SoftwareAG/webmethods-api-control-plane/assets/20128287/a9303937-baaa-4650-a301-6393d24b4ca6)

**Comment by vallabsag** [comment] 2023-09-05 08:06
@thesse1 Please share build number. Unable to reproduce these issues.

**Comment by thesse1** [comment] 2023-09-06 13:28
@vallabsag Yes, it still happens today on Edition : Beta, Version : 10.15.4.0.

It seems to happen when I turn an API Gateway instance on or off. It takes a while until the status is correctly displayed in the Control Plane. The delay is OK, but in between the status displayed in Control Plane is inconsistent, for example: The data plane is still red, although all runtimes are green. It's OK that the status is not updated immediately, but the status displayed should always be consistent. And no, this is not an edge case: People will look at the state indicators exactly when they are (re)starting or stopping an instance.

**Comment by thesse1** [comment] 2023-09-06 13:52
@vallabsag Just found out: You do not even have to (re)start or stop instances. You just log-off and log-on again on the Control Plane. Then you have this strange behavior for some minutes...

**Comment by vallabsag** [comment] 2023-09-06 16:36
@thesse1  Thanks we will take a look and repro this behavior against this version and against recent builds (which is about to be released soon). We will see if this got fixed recently.

**Comment by vallabsag** [comment] 2023-09-07 14:02
Talked to Thomas over a call reg this issue and the issue was more frequently observed when we switch tabs. since the issue is not reproducible in our env, need to verify if any recent issues in this area is fixed in latest fixes. Also, we need to check if issue is due to higher number of runtimes and dataplanes involved in his case. Will repro with the higher numbers.

**Comment by Kumarapandian** [comment] 2023-09-16 00:14
This will be fixed with the latest build. Will update once it is promoted here.

**Closed** 2023-09-16 00:41 UTC
