### ISSUE TITLE
Some panels do not (yet?) show any data

### ISSUE THREAD

**Issue by thesse1** [SoftwareAG/webmethods-api-control-plane#23] opened 2023-08-15 10:43 UTC
![image](https://github.com/SoftwareAG/webmethods-api-control-plane/assets/20128287/c34e5602-47f2-4d20-b057-831fa68aba7d)

![image](https://github.com/SoftwareAG/webmethods-api-control-plane/assets/20128287/9fdb943d-74bd-43e5-9f07-3df4080ab90c)

![image](https://github.com/SoftwareAG/webmethods-api-control-plane/assets/20128287/a07fed54-1f79-412d-b457-8bb61424e3ae)

![image](https://github.com/SoftwareAG/webmethods-api-control-plane/assets/20128287/cfa8d810-cf17-48f7-8726-23bb47d6a8f3)

**Comment by vallabsag** [comment] 2023-08-17 13:17
@thesse1  Is the concern related to these data are not loaded ever or is it that these data are shown empty until they get loaded? 

Please provide more details on the issue and the repro case. 

If this is the 2nd case, we already have a task in pipeline for implementing a shimmering effect and a banner/info message on top to let the user know the data is getting still loaded.

**Comment by vallabsag** [comment] 2023-08-21 11:31
@thesse1 Please let us know the response for my queries. 

Regards,
Vallab.

**Comment by thesse1** [comment] 2023-08-25 06:35
For me, these panels are never populated. Even if I wait for some minutes.

**Comment by vallabsag** [comment] 2023-09-05 07:16
@thesse1 Need more info on the issue for the team to work on the issue. These panels are working fine for us. Please share the build numbers where you see this issue. 

Also, can you please let me know if you tried this in recent versions? is it still seen in recent versions?

**Comment by thesse1** [comment] 2023-09-06 13:23
@vallabsag Yes, I still see this today on Edition : Beta, Version : 10.15.4.0

**Comment by vallabsag** [comment] 2023-09-07 13:59
I talked to @thesse1 today over a call. This issue was because there were no errors in his setup and since default selection in problematic is error rate, this widget appears empty. When other selections like avg resp time are chosen, the problematic widgets works as expected. 

Closing this issue since this is as designed. But the point is taken that this is not immediately understandable to the user. We will revisit this scenario with the UX team and try to enhance the UX experience of such scenarios.

**Closed by vallabsag** 2023-09-07 13:59 UTC
